[package]
name = "commandwave"
version = "0.3.1"
description = "A cross-platform terminal emulator inspired by iTerm2"
authors = ["CommandWave Contributors"]
edition = "2021"

[lib]
name = "commandwave_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.9"
anyhow = "1"
sysinfo = { version = "0.33", default-features = false, features = ["system"] }
toml_edit = "0.25"
tauri-plugin-notifications = "=0.5.0-rc.13"
tauri-plugin-updater = "2"

[profile.release]
codegen-units = 1
lto = true
strip = true
