import type { ITheme } from "@xterm/xterm";

export interface ThemeDef {
  name: string;
  dark: boolean;
  theme: ITheme;
}

/**
 * Built-in color schemes, ported from classic iTerm2 bundles.
 * ANSI order: black, red, green, yellow, blue, magenta, cyan, white.
 */
export const themes: ThemeDef[] = [
  {
    name: "CommandWave Dark",
    dark: true,
    theme: {
      background: "#1a1d23",
      foreground: "#e8eaed",
      cursor: "#4f9cf9",
      cursorAccent: "#1a1d23",
      selectionBackground: "#31445c",
      black: "#282c34",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#ef7c81",
      brightGreen: "#a9d38b",
      brightYellow: "#f0d08d",
      brightBlue: "#71bdff",
      brightMagenta: "#d688ed",
      brightCyan: "#66c6d2",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Dracula",
    dark: true,
    theme: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Solarized Dark",
    dark: true,
    theme: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#93a1a1",
      cursorAccent: "#002b36",
      selectionBackground: "#274642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#657b83",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    name: "Nord",
    dark: true,
    theme: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#2e3440",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    name: "Snazzy",
    dark: true,
    theme: {
      background: "#282a36",
      foreground: "#eff0eb",
      cursor: "#97979b",
      cursorAccent: "#282a36",
      selectionBackground: "#3e4050",
      black: "#282a36",
      red: "#ff5c57",
      green: "#5af78e",
      yellow: "#f3f99d",
      blue: "#57c7ff",
      magenta: "#ff6ac1",
      cyan: "#9aedfe",
      white: "#f1f1f0",
      brightBlack: "#686689",
      brightRed: "#ff5c57",
      brightGreen: "#5af78e",
      brightYellow: "#f3f99d",
      brightBlue: "#57c7ff",
      brightMagenta: "#ff6ac1",
      brightCyan: "#9aedfe",
      brightWhite: "#eff0eb",
    },
  },
  {
    name: "Gruvbox Dark",
    dark: true,
    theme: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#504945",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    name: "GitHub Dark",
    dark: true,
    theme: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      cursor: "#58a6ff",
      cursorAccent: "#0d1117",
      selectionBackground: "#30363d",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#39c5cf",
      white: "#b1bac4",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#56d364",
      brightYellow: "#e3b341",
      brightBlue: "#79c0ff",
      brightMagenta: "#d2a8ff",
      brightCyan: "#56d4dd",
      brightWhite: "#f0f6fc",
    },
  },
  {
    name: "Dark Pastel",
    dark: true,
    theme: {
      background: "#000000",
      foreground: "#ffffff",
      cursor: "#bbbbbb",
      cursorAccent: "#000000",
      selectionBackground: "#414141",
      black: "#000000",
      red: "#ff5555",
      green: "#55ff55",
      yellow: "#ffff55",
      blue: "#5555ff",
      magenta: "#ff55ff",
      cyan: "#55ffff",
      white: "#bbbbbb",
      brightBlack: "#555555",
      brightRed: "#ff5555",
      brightGreen: "#55ff55",
      brightYellow: "#ffff55",
      brightBlue: "#5555ff",
      brightMagenta: "#ff55ff",
      brightCyan: "#55ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Solarized Light",
    dark: false,
    theme: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#586e75",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#93a1a1",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    name: "One Light",
    dark: false,
    theme: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#526fff",
      cursorAccent: "#fafafa",
      selectionBackground: "#d5d6de",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#0184bc",
      magenta: "#a626a4",
      cyan: "#0997b3",
      white: "#fafafa",
      brightBlack: "#4f525e",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "GitHub Light",
    dark: false,
    theme: {
      background: "#ffffff",
      foreground: "#24292f",
      cursor: "#044289",
      cursorAccent: "#ffffff",
      selectionBackground: "#b4d5fe",
      black: "#24292f",
      red: "#d73a49",
      green: "#22863a",
      yellow: "#b08800",
      blue: "#0366d6",
      magenta: "#6f42c1",
      cyan: "#1b7c83",
      white: "#6a737d",
      brightBlack: "#959da5",
      brightRed: "#cb2431",
      brightGreen: "#28a745",
      brightYellow: "#dbab09",
      brightBlue: "#2188ff",
      brightMagenta: "#8a63d2",
      brightCyan: "#3192aa",
      brightWhite: "#d1d5da",
    },
  },
  {
    name: "Catppuccin Latte",
    dark: false,
    theme: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      cursorAccent: "#eff1f5",
      selectionBackground: "#acb0be",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#8839ef",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#8839ef",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    name: "Ayu Light",
    dark: false,
    theme: {
      background: "#fafafa",
      foreground: "#5c6166",
      cursor: "#ff9940",
      cursorAccent: "#fafafa",
      selectionBackground: "#c5d4ec",
      black: "#565b66",
      red: "#f07171",
      green: "#86b300",
      yellow: "#f2ae49",
      blue: "#399ee6",
      magenta: "#a37acc",
      cyan: "#4cbfaf",
      white: "#9aa4ad",
      brightBlack: "#8a9199",
      brightRed: "#f07171",
      brightGreen: "#86b300",
      brightYellow: "#f2ae49",
      brightBlue: "#399ee6",
      brightMagenta: "#a37acc",
      brightCyan: "#4cbfaf",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Gruvbox Light",
    dark: false,
    theme: {
      background: "#fbf1c7",
      foreground: "#3c3836",
      cursor: "#3c3836",
      cursorAccent: "#fbf1c7",
      selectionBackground: "#d5c4a1",
      black: "#3c3836",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#7c6f64",
      brightBlack: "#928374",
      brightRed: "#9d0006",
      brightGreen: "#79740e",
      brightYellow: "#b57614",
      brightBlue: "#076678",
      brightMagenta: "#8f3f71",
      brightCyan: "#427b58",
      brightWhite: "#fbf1c7",
    },
  },
  {
    name: "Tango Light",
    dark: false,
    theme: {
      background: "#ffffff",
      foreground: "#2e3436",
      cursor: "#2e3436",
      cursorAccent: "#ffffff",
      selectionBackground: "#c8dcf0",
      black: "#2e3436",
      red: "#cc0000",
      green: "#4e9a06",
      yellow: "#c4a000",
      blue: "#3465a4",
      magenta: "#75507b",
      cyan: "#06989a",
      white: "#d3d7cf",
      brightBlack: "#555753",
      brightRed: "#ef2929",
      brightGreen: "#8ae234",
      brightYellow: "#fce94f",
      brightBlue: "#729fcf",
      brightMagenta: "#ad7fa8",
      brightCyan: "#34e2e2",
      brightWhite: "#eeeeec",
    },
  },
  {
    name: "Light Background",
    dark: false,
    theme: {
      background: "#ffffff",
      foreground: "#000000",
      cursor: "#555555",
      cursorAccent: "#ffffff",
      selectionBackground: "#c1deff",
      black: "#000000",
      red: "#bb0000",
      green: "#00bb00",
      yellow: "#bbbb00",
      blue: "#0000bb",
      magenta: "#bb00bb",
      cyan: "#00bbbb",
      white: "#bbbbbb",
      brightBlack: "#555555",
      brightRed: "#ff5555",
      brightGreen: "#55ff55",
      brightYellow: "#ffff55",
      brightBlue: "#5555ff",
      brightMagenta: "#ff55ff",
      brightCyan: "#55ffff",
      brightWhite: "#ffffff",
    },
  },
];

export function getTheme(name: string): ITheme {
  return (themes.find((t) => t.name === name) ?? themes[0]).theme;
}

export function isDarkTheme(name: string): boolean {
  return (themes.find((t) => t.name === name) ?? themes[0]).dark;
}

/** Customizable color slots (customColors keys). */
export const COLOR_KEYS = [
  "background",
  "foreground",
  "cursor",
  "cursorAccent",
  "selectionBackground",
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
] as const;

export type ColorKey = (typeof COLOR_KEYS)[number];
export type ColorOverrides = Partial<Record<ColorKey, string>>;

/** Built-in theme with per-slot custom color overrides applied. */
export function resolveTheme(name: string, overrides: ColorOverrides | null | undefined): ITheme {
  const base = { ...getTheme(name) };
  if (!overrides) return base;
  for (const key of COLOR_KEYS) {
    const v = overrides[key];
    if (v) (base as Record<string, string>)[key] = v;
  }
  return base;
}

/**
 * Convert a hex color to rgba with the given alpha (the backgroundOpacity
 * setting). Invalid input returns null so callers can skip.
 */
export function withAlpha(hex: string, alpha: number): string | null {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const a = Math.min(1, Math.max(0, alpha));
  const n = Number.parseInt(m[1], 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${a})`;
}
