import type { ITheme } from "@xterm/xterm";

/** Where a built-in theme came from and the license it ships under. */
export interface ThemeCredit {
  source: string;
  /** SPDX id, or "original" for themes authored in this repository. */
  license: string;
}

export interface ThemeDef {
  name: string;
  dark: boolean;
  /** Upstream project + license. Every theme carries one; see THIRD-PARTY-NOTICES.md. */
  credit: ThemeCredit;
  /** "legacy" = shipped before the licensing audit; "added" = audited in that pass. */
  group: "legacy" | "added";
  theme: ITheme;
}

/**
 * Built-in color schemes. The `legacy` entries were ported from classic iTerm2
 * bundles; the `added` ones come from the iTerm2-Color-Schemes collection
 * (commit 0b55a9e6) with their upstream licenses verified — see
 * THIRD-PARTY-NOTICES.md for per-theme provenance and for the schemes that were
 * rejected during that audit.
 * ANSI order: black, red, green, yellow, blue, magenta, cyan, white.
 */
export const themes: ThemeDef[] = [
  {
    name: "CommandWave Dark",
    dark: true,
    credit: { source: "CommandWave (authored in this repository)", license: "original" },
    group: "legacy",
    theme: {
      background: "#1a1d23",
      foreground: "#e8eaed",
      cursor: "#4f9cf9",
      cursorAccent: "#1a1d23",
      selectionBackground: "#31445c",
      black: "#282c34",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#ef7c81",
      brightGreen: "#a9d38b",
      brightYellow: "#f0d08d",
      brightBlue: "#71bdff",
      brightMagenta: "#d688ed",
      brightCyan: "#66c6d2",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Dracula",
    dark: true,
    credit: { source: "dracula/dracula-theme", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Solarized Dark",
    dark: true,
    credit: { source: "altercation/solarized", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#93a1a1",
      cursorAccent: "#002b36",
      selectionBackground: "#274642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#657b83",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    name: "Snazzy",
    dark: true,
    credit: { source: "sindresorhus/iterm2-snazzy", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#282a36",
      foreground: "#eff0eb",
      cursor: "#97979b",
      cursorAccent: "#282a36",
      selectionBackground: "#3e4050",
      black: "#282a36",
      red: "#ff5c57",
      green: "#5af78e",
      yellow: "#f3f99d",
      blue: "#57c7ff",
      magenta: "#ff6ac1",
      cyan: "#9aedfe",
      white: "#f1f1f0",
      brightBlack: "#686689",
      brightRed: "#ff5c57",
      brightGreen: "#5af78e",
      brightYellow: "#f3f99d",
      brightBlue: "#57c7ff",
      brightMagenta: "#ff6ac1",
      brightCyan: "#9aedfe",
      brightWhite: "#eff0eb",
    },
  },
  {
    name: "Gruvbox Dark",
    dark: true,
    credit: { source: "morhetz/gruvbox (README + package.json declare MIT; no LICENSE file)", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#504945",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    name: "GitHub Dark",
    dark: true,
    credit: { source: "primer/github-vscode-theme", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      cursor: "#58a6ff",
      cursorAccent: "#0d1117",
      selectionBackground: "#30363d",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#39c5cf",
      white: "#b1bac4",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#56d364",
      brightYellow: "#e3b341",
      brightBlue: "#79c0ff",
      brightMagenta: "#d2a8ff",
      brightCyan: "#56d4dd",
      brightWhite: "#f0f6fc",
    },
  },
  {
    name: "Solarized Light",
    dark: false,
    credit: { source: "altercation/solarized", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#586e75",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#93a1a1",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    name: "One Light",
    dark: false,
    credit: { source: "atom/one-light-syntax", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#526fff",
      cursorAccent: "#fafafa",
      selectionBackground: "#d5d6de",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#0184bc",
      magenta: "#a626a4",
      cyan: "#0997b3",
      white: "#fafafa",
      brightBlack: "#4f525e",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "GitHub Light",
    dark: false,
    credit: { source: "primer/github-vscode-theme", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#ffffff",
      foreground: "#24292f",
      cursor: "#044289",
      cursorAccent: "#ffffff",
      selectionBackground: "#b4d5fe",
      black: "#24292f",
      red: "#d73a49",
      green: "#22863a",
      yellow: "#b08800",
      blue: "#0366d6",
      magenta: "#6f42c1",
      cyan: "#1b7c83",
      white: "#6a737d",
      brightBlack: "#959da5",
      brightRed: "#cb2431",
      brightGreen: "#28a745",
      brightYellow: "#dbab09",
      brightBlue: "#2188ff",
      brightMagenta: "#8a63d2",
      brightCyan: "#3192aa",
      brightWhite: "#d1d5da",
    },
  },
  {
    name: "Catppuccin Latte",
    dark: false,
    credit: { source: "catppuccin/catppuccin", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      cursorAccent: "#eff1f5",
      selectionBackground: "#acb0be",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#8839ef",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#8839ef",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    name: "Ayu Light",
    dark: false,
    credit: { source: "ayu-theme/ayu-colors", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#fafafa",
      foreground: "#5c6166",
      cursor: "#ff9940",
      cursorAccent: "#fafafa",
      selectionBackground: "#c5d4ec",
      black: "#565b66",
      red: "#f07171",
      green: "#86b300",
      yellow: "#f2ae49",
      blue: "#399ee6",
      magenta: "#a37acc",
      cyan: "#4cbfaf",
      white: "#9aa4ad",
      brightBlack: "#8a9199",
      brightRed: "#f07171",
      brightGreen: "#86b300",
      brightYellow: "#f2ae49",
      brightBlue: "#399ee6",
      brightMagenta: "#a37acc",
      brightCyan: "#4cbfaf",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Gruvbox Light",
    dark: false,
    credit: { source: "morhetz/gruvbox (README + package.json declare MIT; no LICENSE file)", license: "MIT" },
    group: "legacy",
    theme: {
      background: "#fbf1c7",
      foreground: "#3c3836",
      cursor: "#3c3836",
      cursorAccent: "#fbf1c7",
      selectionBackground: "#d5c4a1",
      black: "#3c3836",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#7c6f64",
      brightBlack: "#928374",
      brightRed: "#9d0006",
      brightGreen: "#79740e",
      brightYellow: "#b57614",
      brightBlue: "#076678",
      brightMagenta: "#8f3f71",
      brightCyan: "#427b58",
      brightWhite: "#fbf1c7",
    },
  },
  {
    name: "Catppuccin Mocha",
    dark: true,
    credit: { source: "catppuccin/catppuccin via iTerm2-Color-Schemes (Catppuccin Mocha)", license: "MIT" },
    group: "added",
    theme: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#f5e0dc",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f7aec2",
      brightGreen: "#c2ecbf",
      brightYellow: "#fcd682",
      brightBlue: "#aeccfc",
      brightMagenta: "#f398da",
      brightCyan: "#b1eae1",
      brightWhite: "#a6adc8",
    },
  },
  {
    name: "Catppuccin Frappe",
    dark: true,
    credit: { source: "catppuccin/catppuccin via iTerm2-Color-Schemes (Catppuccin Frappe)", license: "MIT" },
    group: "added",
    theme: {
      background: "#303446",
      foreground: "#c6d0f5",
      cursor: "#f2d5cf",
      cursorAccent: "#303446",
      selectionBackground: "#f2d5cf",
      black: "#51576d",
      red: "#e78284",
      green: "#a6d189",
      yellow: "#e5c890",
      blue: "#8caaee",
      magenta: "#f4b8e4",
      cyan: "#81c8be",
      white: "#b5bfe2",
      brightBlack: "#626880",
      brightRed: "#eda0a2",
      brightGreen: "#b9dba2",
      brightYellow: "#ecd7ae",
      brightBlue: "#adc2f3",
      brightMagenta: "#f38ed8",
      brightCyan: "#98d2ca",
      brightWhite: "#a5adce",
    },
  },
  {
    name: "Catppuccin Macchiato",
    dark: true,
    credit: { source: "catppuccin/catppuccin via iTerm2-Color-Schemes (Catppuccin Macchiato)", license: "MIT" },
    group: "added",
    theme: {
      background: "#24273a",
      foreground: "#cad3f5",
      cursor: "#f4dbd6",
      cursorAccent: "#24273a",
      selectionBackground: "#f4dbd6",
      black: "#494d64",
      red: "#ed8796",
      green: "#a6da95",
      yellow: "#eed49f",
      blue: "#8aadf4",
      magenta: "#f5bde6",
      cyan: "#8bd5ca",
      white: "#b8c0e0",
      brightBlack: "#5b6078",
      brightRed: "#f2a7b2",
      brightGreen: "#bde3b0",
      brightYellow: "#f4e3c1",
      brightBlue: "#adc5f7",
      brightMagenta: "#f493da",
      brightCyan: "#a5ded6",
      brightWhite: "#a5adcb",
    },
  },
  {
    name: "Tokyo Night",
    dark: true,
    credit: { source: "folke/tokyonight.nvim via iTerm2-Color-Schemes (TokyoNight)", license: "Apache-2.0" },
    group: "added",
    theme: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#15161e",
      selectionBackground: "#33467c",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  {
    name: "Rosé Pine",
    dark: true,
    credit: { source: "rose-pine/rose-pine-theme via iTerm2-Color-Schemes (Rose Pine)", license: "MIT" },
    group: "added",
    theme: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#e0def4",
      cursorAccent: "#191724",
      selectionBackground: "#403d52",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },
  {
    name: "Rosé Pine Moon",
    dark: true,
    credit: { source: "rose-pine/rose-pine-theme via iTerm2-Color-Schemes (Rose Pine Moon)", license: "MIT" },
    group: "added",
    theme: {
      background: "#232136",
      foreground: "#e0def4",
      cursor: "#e0def4",
      cursorAccent: "#232136",
      selectionBackground: "#44415a",
      black: "#393552",
      red: "#eb6f92",
      green: "#3e8fb0",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ea9a97",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#3e8fb0",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ea9a97",
      brightWhite: "#e0def4",
    },
  },
  {
    name: "Kanagawa Wave",
    dark: true,
    credit: { source: "rebelot/kanagawa.nvim via iTerm2-Color-Schemes (Kanagawa Wave)", license: "MIT" },
    group: "added",
    theme: {
      background: "#1f1f28",
      foreground: "#dcd7ba",
      cursor: "#dcd7ba",
      cursorAccent: "#1f1f28",
      selectionBackground: "#dcd7ba",
      black: "#090618",
      red: "#c34043",
      green: "#76946a",
      yellow: "#c0a36e",
      blue: "#7e9cd8",
      magenta: "#957fb8",
      cyan: "#6a9589",
      white: "#c8c093",
      brightBlack: "#727169",
      brightRed: "#e82424",
      brightGreen: "#98bb6c",
      brightYellow: "#e6c384",
      brightBlue: "#7fb4ca",
      brightMagenta: "#938aa9",
      brightCyan: "#7aa89f",
      brightWhite: "#dcd7ba",
    },
  },
  {
    name: "Kanagawa Dragon",
    dark: true,
    credit: { source: "rebelot/kanagawa.nvim via iTerm2-Color-Schemes (Kanagawa Dragon)", license: "MIT" },
    group: "added",
    theme: {
      background: "#181616",
      foreground: "#c5c9c5",
      cursor: "#c8c093",
      cursorAccent: "#181616",
      selectionBackground: "#c5c9c5",
      black: "#0d0c0c",
      red: "#c4746e",
      green: "#8a9a7b",
      yellow: "#c4b28a",
      blue: "#8ba4b0",
      magenta: "#a292a3",
      cyan: "#8ea4a2",
      white: "#c8c093",
      brightBlack: "#a6a69c",
      brightRed: "#e46876",
      brightGreen: "#87a987",
      brightYellow: "#e6c384",
      brightBlue: "#7fb4ca",
      brightMagenta: "#938aa9",
      brightCyan: "#7aa89f",
      brightWhite: "#c5c9c5",
    },
  },
  {
    name: "Night Owl",
    dark: true,
    credit: { source: "sdras/night-owl-vscode-theme (iTerm port by zasdaym) via iTerm2-Color-Schemes (Night Owl)", license: "MIT" },
    group: "added",
    theme: {
      background: "#011627",
      foreground: "#d6deeb",
      cursor: "#7e57c2",
      cursorAccent: "#ffffff",
      selectionBackground: "#5f7e97",
      black: "#011627",
      red: "#ef5350",
      green: "#22da6e",
      yellow: "#addb67",
      blue: "#82aaff",
      magenta: "#c792ea",
      cyan: "#21c7a8",
      white: "#ffffff",
      brightBlack: "#575656",
      brightRed: "#ef5350",
      brightGreen: "#22da6e",
      brightYellow: "#ffeb95",
      brightBlue: "#82aaff",
      brightMagenta: "#c792ea",
      brightCyan: "#7fdbca",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "One Dark",
    dark: true,
    credit: { source: "atom/one-dark-syntax via iTerm2-Color-Schemes (Atom One Dark)", license: "MIT" },
    group: "added",
    theme: {
      background: "#21252b",
      foreground: "#abb2bf",
      cursor: "#abb2bf",
      cursorAccent: "#21252b",
      selectionBackground: "#323844",
      black: "#21252b",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#767676",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#abb2bf",
    },
  },
  {
    name: "Iceberg Dark",
    dark: true,
    credit: { source: "cocopon/iceberg.vim via iTerm2-Color-Schemes (Iceberg Dark)", license: "MIT" },
    group: "added",
    theme: {
      background: "#161821",
      foreground: "#c6c8d1",
      cursor: "#c6c8d1",
      cursorAccent: "#161821",
      selectionBackground: "#c6c8d1",
      black: "#1e2132",
      red: "#e27878",
      green: "#b4be82",
      yellow: "#e2a478",
      blue: "#84a0c6",
      magenta: "#a093c7",
      cyan: "#89b8c2",
      white: "#c6c8d1",
      brightBlack: "#6b7089",
      brightRed: "#e98989",
      brightGreen: "#c0ca8e",
      brightYellow: "#e9b189",
      brightBlue: "#91acd1",
      brightMagenta: "#ada0d3",
      brightCyan: "#95c4ce",
      brightWhite: "#d2d4de",
    },
  },
  {
    name: "Nightfox",
    dark: true,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Nightfox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#192330",
      foreground: "#cdcecf",
      cursor: "#cdcecf",
      cursorAccent: "#192330",
      selectionBackground: "#2b3b51",
      black: "#393b44",
      red: "#c94f6d",
      green: "#81b29a",
      yellow: "#dbc074",
      blue: "#719cd6",
      magenta: "#9d79d6",
      cyan: "#63cdcf",
      white: "#dfdfe0",
      brightBlack: "#575860",
      brightRed: "#d16983",
      brightGreen: "#8ebaa4",
      brightYellow: "#e0c989",
      brightBlue: "#86abdc",
      brightMagenta: "#baa1e2",
      brightCyan: "#7ad5d6",
      brightWhite: "#e4e4e5",
    },
  },
  {
    name: "Nordfox",
    dark: true,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Nordfox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#2e3440",
      foreground: "#cdcecf",
      cursor: "#cdcecf",
      cursorAccent: "#2e3440",
      selectionBackground: "#3e4a5b",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#465780",
      brightRed: "#d06f79",
      brightGreen: "#b1d196",
      brightYellow: "#f0d399",
      brightBlue: "#8cafd2",
      brightMagenta: "#c895bf",
      brightCyan: "#93ccdc",
      brightWhite: "#e7ecf4",
    },
  },
  {
    name: "Duskfox",
    dark: true,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Duskfox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#232136",
      foreground: "#e0def4",
      cursor: "#e0def4",
      cursorAccent: "#232136",
      selectionBackground: "#433c59",
      black: "#393552",
      red: "#eb6f92",
      green: "#a3be8c",
      yellow: "#f6c177",
      blue: "#569fba",
      magenta: "#c4a7e7",
      cyan: "#9ccfd8",
      white: "#e0def4",
      brightBlack: "#47407d",
      brightRed: "#f083a2",
      brightGreen: "#b1d196",
      brightYellow: "#f9cb8c",
      brightBlue: "#65b1cd",
      brightMagenta: "#ccb1ed",
      brightCyan: "#a6dae3",
      brightWhite: "#e2e0f7",
    },
  },
  {
    name: "Terafox",
    dark: true,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Terafox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#152528",
      foreground: "#e6eaea",
      cursor: "#e6eaea",
      cursorAccent: "#152528",
      selectionBackground: "#293e40",
      black: "#2f3239",
      red: "#e85c51",
      green: "#7aa4a1",
      yellow: "#fda47f",
      blue: "#5a93aa",
      magenta: "#ad5c7c",
      cyan: "#a1cdd8",
      white: "#ebebeb",
      brightBlack: "#4e5157",
      brightRed: "#eb746b",
      brightGreen: "#8eb2af",
      brightYellow: "#fdb292",
      brightBlue: "#73a3b7",
      brightMagenta: "#b97490",
      brightCyan: "#afd4de",
      brightWhite: "#eeeeee",
    },
  },
  {
    name: "Sonokai",
    dark: true,
    credit: { source: "sainnhe/sonokai via iTerm2-Color-Schemes (Sonokai)", license: "MIT" },
    group: "added",
    theme: {
      background: "#2c2e34",
      foreground: "#e2e2e3",
      cursor: "#e2e2e3",
      cursorAccent: "#2c2e34",
      selectionBackground: "#414550",
      black: "#181819",
      red: "#fc5d7c",
      green: "#9ed072",
      yellow: "#e7c664",
      blue: "#76cce0",
      magenta: "#b39df3",
      cyan: "#f39660",
      white: "#e2e2e3",
      brightBlack: "#7f8490",
      brightRed: "#fc5d7c",
      brightGreen: "#9ed072",
      brightYellow: "#e7c664",
      brightBlue: "#76cce0",
      brightMagenta: "#b39df3",
      brightCyan: "#f39660",
      brightWhite: "#e2e2e3",
    },
  },
  {
    name: "Tomorrow Night",
    dark: true,
    credit: { source: "chriskempson/tomorrow-theme via iTerm2-Color-Schemes (Tomorrow Night)", license: "MIT" },
    group: "added",
    theme: {
      background: "#1d1f21",
      foreground: "#c5c8c6",
      cursor: "#c5c8c6",
      cursorAccent: "#1d1f21",
      selectionBackground: "#373b41",
      black: "#000000",
      red: "#cc6666",
      green: "#b5bd68",
      yellow: "#f0c674",
      blue: "#81a2be",
      magenta: "#b294bb",
      cyan: "#8abeb7",
      white: "#ffffff",
      brightBlack: "#000000",
      brightRed: "#cc6666",
      brightGreen: "#b5bd68",
      brightYellow: "#f0c674",
      brightBlue: "#81a2be",
      brightMagenta: "#b294bb",
      brightCyan: "#8abeb7",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Doom One",
    dark: true,
    credit: { source: "doomemacs/themes via iTerm2-Color-Schemes (Doom One)", license: "MIT" },
    group: "added",
    theme: {
      background: "#282c34",
      foreground: "#bbc2cf",
      cursor: "#51afef",
      cursorAccent: "#1b1b1b",
      selectionBackground: "#42444b",
      black: "#000000",
      red: "#ff6c6b",
      green: "#98be65",
      yellow: "#ecbe7b",
      blue: "#a9a1e1",
      magenta: "#c678dd",
      cyan: "#51afef",
      white: "#bbc2cf",
      brightBlack: "#000000",
      brightRed: "#ff6655",
      brightGreen: "#99bb66",
      brightYellow: "#ecbe7b",
      brightBlue: "#a9a1e1",
      brightMagenta: "#c678dd",
      brightCyan: "#51afef",
      brightWhite: "#bfbfbf",
    },
  },
  {
    name: "Ayu Mirage",
    dark: true,
    credit: { source: "ayu-theme/ayu-colors via iTerm2-Color-Schemes (Ayu Mirage)", license: "MIT" },
    group: "added",
    theme: {
      background: "#1f2430",
      foreground: "#cccac2",
      cursor: "#ffcc66",
      cursorAccent: "#1f2430",
      selectionBackground: "#409fff",
      black: "#171b24",
      red: "#ed8274",
      green: "#87d96c",
      yellow: "#facc6e",
      blue: "#6dcbfa",
      magenta: "#dabafa",
      cyan: "#90e1c6",
      white: "#c7c7c7",
      brightBlack: "#686868",
      brightRed: "#f28779",
      brightGreen: "#d5ff80",
      brightYellow: "#ffd173",
      brightBlue: "#73d0ff",
      brightMagenta: "#dfbfff",
      brightCyan: "#95e6cb",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Gruvbox Material Dark",
    dark: true,
    credit: { source: "sainnhe/gruvbox-material via iTerm2-Color-Schemes (Gruvbox Material Dark)", license: "MIT" },
    group: "added",
    theme: {
      background: "#282828",
      foreground: "#d4be98",
      cursor: "#d4be98",
      cursorAccent: "#282828",
      selectionBackground: "#d4be98",
      black: "#282828",
      red: "#ea6962",
      green: "#a9b665",
      yellow: "#d8a657",
      blue: "#7daea3",
      magenta: "#d3869b",
      cyan: "#89b482",
      white: "#d4be98",
      brightBlack: "#7c6f64",
      brightRed: "#ea6962",
      brightGreen: "#a9b665",
      brightYellow: "#d8a657",
      brightBlue: "#7daea3",
      brightMagenta: "#d3869b",
      brightCyan: "#89b482",
      brightWhite: "#ddc7a1",
    },
  },
  {
    name: "Rosé Pine Dawn",
    dark: false,
    credit: { source: "rose-pine/rose-pine-theme via iTerm2-Color-Schemes (Rose Pine Dawn)", license: "MIT" },
    group: "added",
    theme: {
      background: "#faf4ed",
      foreground: "#575279",
      cursor: "#575279",
      cursorAccent: "#faf4ed",
      selectionBackground: "#dfdad9",
      black: "#f2e9e1",
      red: "#b4637a",
      green: "#286983",
      yellow: "#ea9d34",
      blue: "#56949f",
      magenta: "#907aa9",
      cyan: "#d7827e",
      white: "#575279",
      brightBlack: "#9893a5",
      brightRed: "#b4637a",
      brightGreen: "#286983",
      brightYellow: "#ea9d34",
      brightBlue: "#56949f",
      brightMagenta: "#907aa9",
      brightCyan: "#d7827e",
      brightWhite: "#575279",
    },
  },
  {
    name: "Kanagawa Lotus",
    dark: false,
    credit: { source: "rebelot/kanagawa.nvim via iTerm2-Color-Schemes (Kanagawa Lotus)", license: "MIT" },
    group: "added",
    theme: {
      background: "#f2ecbc",
      foreground: "#545464",
      cursor: "#43436c",
      cursorAccent: "#f2ecbc",
      selectionBackground: "#545464",
      black: "#1f1f28",
      red: "#c84053",
      green: "#6f894e",
      yellow: "#77713f",
      blue: "#4d699b",
      magenta: "#b35b79",
      cyan: "#597b75",
      white: "#545464",
      brightBlack: "#8a8980",
      brightRed: "#d7474b",
      brightGreen: "#6e915f",
      brightYellow: "#836f4a",
      brightBlue: "#6693bf",
      brightMagenta: "#624c83",
      brightCyan: "#5e857a",
      brightWhite: "#43436c",
    },
  },
  {
    name: "Iceberg Light",
    dark: false,
    credit: { source: "cocopon/iceberg.vim via iTerm2-Color-Schemes (Iceberg Light)", license: "MIT" },
    group: "added",
    theme: {
      background: "#e8e9ec",
      foreground: "#33374c",
      cursor: "#33374c",
      cursorAccent: "#e8e9ec",
      selectionBackground: "#33374c",
      black: "#dcdfe7",
      red: "#cc517a",
      green: "#668e3d",
      yellow: "#c57339",
      blue: "#2d539e",
      magenta: "#7759b4",
      cyan: "#3f83a6",
      white: "#33374c",
      brightBlack: "#8389a3",
      brightRed: "#cc3768",
      brightGreen: "#598030",
      brightYellow: "#b6662d",
      brightBlue: "#22478e",
      brightMagenta: "#6845ad",
      brightCyan: "#327698",
      brightWhite: "#262a3f",
    },
  },
  {
    name: "One Half Light",
    dark: false,
    credit: { source: "sonph/onehalf via iTerm2-Color-Schemes (One Half Light)", license: "MIT" },
    group: "added",
    theme: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#bfceff",
      cursorAccent: "#383a42",
      selectionBackground: "#bfceff",
      black: "#383a42",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#0184bc",
      magenta: "#a626a4",
      cyan: "#0997b3",
      white: "#fafafa",
      brightBlack: "#4f525e",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    name: "Light Owl",
    dark: false,
    credit: { source: "sdras/night-owl-vscode-theme (iTerm port by zasdaym) via iTerm2-Color-Schemes (Light Owl)", license: "MIT" },
    group: "added",
    theme: {
      background: "#fbfbfb",
      foreground: "#403f53",
      cursor: "#403f53",
      cursorAccent: "#f6f6f6",
      selectionBackground: "#e0e0e0",
      black: "#403f53",
      red: "#de3d3b",
      green: "#08916a",
      yellow: "#e0af02",
      blue: "#288ed7",
      magenta: "#d6438a",
      cyan: "#2aa298",
      white: "#f0f0f0",
      brightBlack: "#989fb1",
      brightRed: "#de3d3b",
      brightGreen: "#08916a",
      brightYellow: "#daaa01",
      brightBlue: "#288ed7",
      brightMagenta: "#d6438a",
      brightCyan: "#2aa298",
      brightWhite: "#f0f0f0",
    },
  },
  {
    name: "Dayfox",
    dark: false,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Dayfox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#f6f2ee",
      foreground: "#3d2b5a",
      cursor: "#3d2b5a",
      cursorAccent: "#f6f2ee",
      selectionBackground: "#e7d2be",
      black: "#352c24",
      red: "#a5222f",
      green: "#396847",
      yellow: "#ac5402",
      blue: "#2848a9",
      magenta: "#6e33ce",
      cyan: "#287980",
      white: "#f2e9e1",
      brightBlack: "#534c45",
      brightRed: "#b3434e",
      brightGreen: "#577f63",
      brightYellow: "#b86e28",
      brightBlue: "#4863b6",
      brightMagenta: "#8452d5",
      brightCyan: "#488d93",
      brightWhite: "#f4ece6",
    },
  },
  {
    name: "Dawnfox",
    dark: false,
    credit: { source: "EdenEast/nightfox.nvim via iTerm2-Color-Schemes (Dawnfox)", license: "MIT" },
    group: "added",
    theme: {
      background: "#faf4ed",
      foreground: "#575279",
      cursor: "#575279",
      cursorAccent: "#faf4ed",
      selectionBackground: "#d0d8d8",
      black: "#575279",
      red: "#b4637a",
      green: "#618774",
      yellow: "#ea9d34",
      blue: "#286983",
      magenta: "#907aa9",
      cyan: "#56949f",
      white: "#e5e9f0",
      brightBlack: "#5f5695",
      brightRed: "#c26d85",
      brightGreen: "#629f81",
      brightYellow: "#eea846",
      brightBlue: "#2d81a3",
      brightMagenta: "#9a80b9",
      brightCyan: "#5ca7b4",
      brightWhite: "#e6ebf3",
    },
  },
  {
    name: "Gruvbox Material Light",
    dark: false,
    credit: { source: "sainnhe/gruvbox-material via iTerm2-Color-Schemes (Gruvbox Material Light)", license: "MIT" },
    group: "added",
    theme: {
      background: "#fbf1c7",
      foreground: "#654735",
      cursor: "#654735",
      cursorAccent: "#fbf1c7",
      selectionBackground: "#654735",
      black: "#fbf1c7",
      red: "#c14a4a",
      green: "#6c782e",
      yellow: "#b47109",
      blue: "#45707a",
      magenta: "#945e80",
      cyan: "#4c7a5d",
      white: "#654735",
      brightBlack: "#a89984",
      brightRed: "#c14a4a",
      brightGreen: "#6c782e",
      brightYellow: "#b47109",
      brightBlue: "#45707a",
      brightMagenta: "#945e80",
      brightCyan: "#4c7a5d",
      brightWhite: "#4f3829",
    },
  },
  {
    name: "Selenized Light",
    dark: false,
    credit: { source: "jan-warchol/selenized via iTerm2-Color-Schemes (Selenized Light)", license: "MIT" },
    group: "added",
    theme: {
      background: "#fbf3db",
      foreground: "#53676d",
      cursor: "#53676d",
      cursorAccent: "#fbf3db",
      selectionBackground: "#ece3cc",
      black: "#ece3cc",
      red: "#d2212d",
      green: "#489100",
      yellow: "#ad8900",
      blue: "#0072d4",
      magenta: "#ca4898",
      cyan: "#009c8f",
      white: "#53676d",
      brightBlack: "#909995",
      brightRed: "#cc1729",
      brightGreen: "#428b00",
      brightYellow: "#a78300",
      brightBlue: "#006dce",
      brightMagenta: "#c44392",
      brightCyan: "#00978a",
      brightWhite: "#3a4d53",
    },
  },
  {
    name: "Tomorrow",
    dark: false,
    credit: { source: "chriskempson/tomorrow-theme via iTerm2-Color-Schemes (Tomorrow)", license: "MIT" },
    group: "added",
    theme: {
      background: "#ffffff",
      foreground: "#4d4d4c",
      cursor: "#4d4d4c",
      cursorAccent: "#ffffff",
      selectionBackground: "#d6d6d6",
      black: "#000000",
      red: "#c82829",
      green: "#718c00",
      yellow: "#eab700",
      blue: "#4271ae",
      magenta: "#8959a8",
      cyan: "#3e999f",
      white: "#ffffff",
      brightBlack: "#000000",
      brightRed: "#c82829",
      brightGreen: "#718c00",
      brightYellow: "#eab700",
      brightBlue: "#4271ae",
      brightMagenta: "#8959a8",
      brightCyan: "#3e999f",
      brightWhite: "#ffffff",
    },
  },
];

export function getTheme(name: string): ITheme {
  return (themes.find((t) => t.name === name) ?? themes[0]).theme;
}

export function isDarkTheme(name: string): boolean {
  return (themes.find((t) => t.name === name) ?? themes[0]).dark;
}

/** Built-in themes of one polarity, in declaration order. */
export function themesByPolarity(dark: boolean): ThemeDef[] {
  return themes.filter((t) => t.dark === dark);
}

/** Customizable color slots (customColors keys). */
export const COLOR_KEYS = [
  "background",
  "foreground",
  "cursor",
  "cursorAccent",
  "selectionBackground",
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
] as const;

export type ColorKey = (typeof COLOR_KEYS)[number];
export type ColorOverrides = Partial<Record<ColorKey, string>>;

/** Built-in theme with per-slot custom color overrides applied. */
export function resolveTheme(name: string, overrides: ColorOverrides | null | undefined): ITheme {
  const base = { ...getTheme(name) };
  if (!overrides) return base;
  for (const key of COLOR_KEYS) {
    const v = overrides[key];
    if (v) (base as Record<string, string>)[key] = v;
  }
  return base;
}

/**
 * Convert a hex color to rgba with the given alpha (the backgroundOpacity
 * setting). Invalid input returns null so callers can skip.
 */
export function withAlpha(hex: string, alpha: number): string | null {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return null;
  const a = Math.min(1, Math.max(0, alpha));
  const n = Number.parseInt(m[1], 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${a})`;
}

/** Licenses a built-in theme is allowed to declare (see THIRD-PARTY-NOTICES.md). */
export const LICENSE_WHITELIST = [
  "MIT",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "CC0-1.0",
  "Unlicense",
  "original",
] as const;

/**
 * Themes dropped in the licensing audit, mapped to the built-in that replaces
 * them. `null` means "no credible same-family replacement": those fall back to
 * the default theme. Recorded in THIRD-PARTY-NOTICES.md.
 */
export const removedThemeAliases: Record<string, string | null> = {
  Nord: "Nordfox",
  "Dark Pastel": null,
  "Tango Light": null,
  "Light Background": null,
};

/**
 * Rewrite a persisted theme name that no longer exists. Returns the replacement
 * name, or null when the stored name is still valid (nothing to migrate).
 */
export function migrateThemeName(name: string | null | undefined): string | null {
  if (!name) return null;
  if (themes.some((t) => t.name === name)) return null;
  return removedThemeAliases[name] ?? themes[0].name;
}
