// CommandWave agent notifications for Amp (Sourcegraph).
// Generated by the CommandWave desktop app; safe to delete at any time.
import { spawn } from "node:child_process";

const BIN = "{BIN}";

function report(event: string): void {
  try {
    const child = spawn(BIN, ["--agent-event", event], {
      detached: true,
      stdio: "ignore",
      env: process.env,
    });
    child.unref();
  } catch {
    // CommandWave not running — nothing to report.
  }
}

export default function commandwaveNotify(amp: any): void {
  amp.on("session.start", () => report("working"));
  amp.on("agent.start", () => report("working"));
  amp.on("agent.end", (event: any) => {
    const status = String(event?.status ?? "").toLowerCase();
    report(status.includes("error") || status.includes("fail") ? "error" : "finished");
  });
  amp.on("tool.call", () => report("working"));
}
