// CommandWave agent notifications for OpenCode.
// Generated by the CommandWave desktop app; safe to delete at any time.
// Forwards OpenCode lifecycle events to the running CommandWave instance via
// the app binary's `--agent-event` hook CLI.
import { spawn } from "node:child_process";

const BIN = "{BIN}";

function report(event) {
  try {
    const child = spawn(BIN, ["--agent-event", event], {
      detached: true,
      stdio: "ignore",
      env: process.env,
    });
    child.unref();
  } catch {
    // CommandWave not running — nothing to report.
  }
}

export const CommandWaveNotify = async () => ({
  event: async ({ event }) => {
    switch (event?.type) {
      case "permission.asked":
      case "permission.updated":
        report("needs-confirmation");
        break;
      case "session.idle":
        report("finished");
        break;
      case "session.error":
        report("error");
        break;
      case "session.status":
        if (event?.properties?.status === "working") report("working");
        break;
      default:
        break;
    }
  },
});
