// CommandWave agent notifications for Pi.
// Generated by the CommandWave desktop app; safe to delete at any time.
import { spawn } from "node:child_process";

const BIN = "{BIN}";

function report(event: string): void {
  try {
    const child = spawn(BIN, ["--agent-event", event], {
      detached: true,
      stdio: "ignore",
      env: process.env,
    });
    child.unref();
  } catch {
    // CommandWave not running — nothing to report.
  }
}

export default {
  name: "commandwave-notify",
  hooks: {
    onEvent(event: any): void {
      switch (event?.type) {
        case "agent_start":
        case "turn_start":
        case "tool_call":
          report("working");
          break;
        case "ui_prompt_start":
          report("needs-confirmation");
          break;
        case "agent_settled":
        case "agent_end":
          report("finished");
          break;
        case "error":
          report("error");
          break;
        default:
          break;
      }
    },
  },
};
